In [1]:
import numpy as np
import pandas as pd

Выгрузка датасета визитов:

In [2]:
df=pd.read_excel('2023-10-12 11_43_22.xlsx')
df

,SUBJ_ID,SITE_ID,SUBJ_SCREEN,RAND_NUM,INIT,FINSTAT,BLOCK,DEL,SD_01_SDSTAT,CRA Status,...,CRA Status.1198,EOS_01_DECOD,CRA Status.1199,EOS_01_DISCONT,CRA Status.1200,EOS_01_DISCONT_EXCL,CRA Status.1201,EOS_01_DISCONT_OTH,CRA Status.1202,INVESTIGATOR_SIGNATURE
0,Код субъекта,Номер центра,Скрининговый номер,Рандомизационный код,Инициалы Пациента,NaN,NaN,NaN,"Форма не применима, так как заполнена бумажная...",CRA Status,...,CRA Status,Статус в конце исследования,CRA Status,Не закончил/прекратил из-за,CRA Status,Укажите применимые критерии,CRA Status,Укажите,CRA Status,Подпись исследователя
1,6590,01,01001,606,ВТП,NaN,NaN,NaN,NaN,NaN,...,true,Закончил исследование полностью,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6595,01,01002,214,ЗНБ,NaN,NaN,NaN,NaN,NaN,...,true,Закончил исследование полностью,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6608,01,01003,636,ГДЮ,NaN,NaN,NaN,NaN,NaN,...,true,Закончил исследование полностью,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6700,01,01004,641,ДАА,NaN,NaN,NaN,NaN,NaN,...,true,Закончил исследование полностью,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,7719,48,48010,731,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,7724,48,48011,009,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,7725,48,48012,880,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,7734,48,48013,024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,7736,48,48014,953,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
Dict = df[:1].reset_index(drop = True).to_dict('list')
#список всех индексов в бд
listIN=list(df.columns)

Отбор всех DTC:

In [4]:
df_base=df[[ 'SITE_ID','SUBJ_SCREEN']]
df_base

          SITE_ID         SUBJ_SCREEN
0    Номер центра  Скрининговый номер
1              01               01001
2              01               01002
3              01               01003
4              01               01004
..            ...                 ...
492            48               48010
493            48               48011
494            48               48012
495            48               48013
496            48               48014

[497 rows x 2 columns]

In [5]:
Dtc = list(filter(lambda x: x.endswith('DTC'), listIN))

In [6]:
df_dtc = pd.concat([df_base, df[Dtc]], axis=1)
df_dtc

,SITE_ID,SUBJ_SCREEN,V0_02_RFICDTC,V0_04_PEDTC,V0_05_VSDTC,V0_12_LBDTC,V1_01_SVSTDTC,V1_02_LBDTC,V1_06_EXDTC,V3_01_SVSTDTC,V3_09_LBDTC,V4_01_SVSTDTC,V4_09_LBDTC,V5_01_SVSTDTC,V5_09_LBDTC
0,Номер центра,Скрининговый номер,Дата и время подписания Информированного согласия,Дата и время проведения,Дата и время проведения,Дата и время проведения,Дата и время,Дата и время проведения,Дата и время применения,Дата и время,Дата и время проведения,Дата и время,Дата и время проведения,Дата и время,Дата и время проведения
1,01,01001,2023-01-17 09:00,2023-01-17 10:00,2023-01-17 10:00,2023-01-17 11:30,2023-01-18 10:00,NaN,2023-01-18 12:50,2023-02-15 09:00,2023-02-15 11:20,2023-07-07 09:00,2023-07-07 10:00,NaN,NaN
2,01,01002,2023-01-18 08:00,2023-01-18 09:10,2023-01-18 09:10,2023-01-18 11:40,2023-01-19 08:43,NaN,2023-01-19 16:00,2023-02-17 09:40,2023-02-17 10:20,2023-07-07 10:20,2023-07-07 11:00,NaN,NaN
3,01,01003,2023-01-24 09:00,2023-01-24 10:20,2023-01-24 10:00,2023-01-24 11:10,2023-01-26 09:00,NaN,2023-01-26 12:40,2023-02-22 09:20,2023-02-22 11:00,2023-07-12 09:00,2023-07-12 10:10,NaN,NaN
4,01,01004,2023-02-07 08:20,2023-02-07 09:20,2023-02-07 08:50,2023-02-07 10:55,2023-02-09 09:20,NaN,2023-02-09 11:30,2023-03-10 09:40,2023-03-10 10:30,2023-07-31 09:40,2023-07-31 11:20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,48,48010,2023-06-27 14:00,2023-06-27 17:56,2023-06-27 17:56,2023-06-27 18:45,2023-06-28 07:30,2023-06-28 07:54,2023-06-28 11:40,2023-07-31 10:25,2023-07-31 11:15,NaN,NaN,NaN,NaN
493,48,48011,2023-06-28 12:25,2023-06-28 20:06,2023-06-28 20:06,2023-06-28 20:35,2023-06-30 07:00,2023-06-30 07:21,2023-06-30 11:20,2023-07-30 10:00,2023-07-30 11:30,NaN,NaN,NaN,NaN
494,48,48012,2023-06-28 13:35,2023-06-28 16:20,2023-06-28 16:20,2023-06-28 18:08,2023-06-29 07:30,2023-06-29 07:00,2023-06-29 17:37,2023-08-10 10:40,2023-08-10 11:55,NaN,NaN,NaN,NaN
495,48,48013,2023-06-30 11:25,2023-06-30 15:30,2023-06-30 15:30,2023-06-30 17:10,2023-07-03 07:42,2023-07-03 08:26,2023-07-03 12:30,2023-08-02 09:45,2023-08-02 10:40,NaN,NaN,NaN,NaN
496,48,48014,2023-06-30 12:20,2023-06-30 17:05,2023-06-30 17:05,2023-06-30 18:25,2023-07-04 08:00,2023-07-04 08:28,2023-07-04 11:44,2023-07-28 11:50,2023-07-28 13:20,NaN,NaN,NaN,NaN

Отбор всех DAT:

In [7]:
Dat = list(filter(lambda x: x.endswith('DAT'), listIN))
df_dat = pd.concat([df_base, df[Dat]], axis=1)
df_dat

,SITE_ID,SUBJ_SCREEN,SD_01_AMBDAT,V0_01_SVSTDAT,V0_02_BRTHDAT,V0_06_LBDAT,V0_07_LBDAT,V0_08_LBDAT,V0_09_LBDAT,V0_10_LBDAT,...,V5_04_LBDAT,V5_05_LBDAT,V5_06_LBDAT,V5_07_LBDAT,V5_08_LBDAT,V5_10_LBDAT,V5_11_EGDAT,V5_12_QSDAT,V5_14_PRDAT,EOS_01_ENDAT
0,Номер центра,Скрининговый номер,Дата регистрации настоящего приложения к амбул...,Дата визита,Дата рождения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,...,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата проведения,Дата завершения участия в исследовании
1,01,01001,NaN,2023-01-17,1949-03-19,2023-01-18,2023-01-17,2023-01-17,2023-01-17,2023-01-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-07
2,01,01002,NaN,2023-01-18,1962-08-12,2023-01-18,2023-01-18,2023-01-18,2023-01-18,2023-01-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-07
3,01,01003,NaN,2023-01-24,1994-03-31,2023-01-26,2023-01-26,2023-01-26,2023-01-24,2023-01-24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-12
4,01,01004,NaN,2023-02-07,1971-05-08,2023-02-08,2023-02-08,2023-02-08,2023-02-07,2023-02-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,48,48010,NaN,2023-06-27,1955-01-16,2023-06-27,2023-06-27,2023-06-27,2023-06-27,2023-06-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,48,48011,NaN,2023-06-28,1971-05-18,2023-06-28,2023-06-28,2023-06-28,2023-06-29,2023-06-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,48,48012,NaN,2023-06-28,1950-03-02,2023-06-28,2023-06-28,2023-06-28,2023-06-29,2023-06-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,48,48013,NaN,2023-06-30,1958-03-13,2023-06-30,2023-06-30,2023-06-30,2023-06-30,2023-06-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,48,48014,NaN,2023-06-30,1959-10-08,2023-07-01,2023-07-01,2023-07-01,2023-06-30,2023-06-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Отбор Времени:

In [8]:
Tim = list(filter(lambda x: x.endswith('TIM'), listIN))
df_tim = pd.concat([df_base, df[Tim]], axis=1)
df_tim

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Результат теста на ковид:

In [9]:
Mborres = list(filter(lambda x: x.endswith('MBORRES'), listIN))
df_mborres = pd.concat([df_base, df[Mborres]], axis=1)
df_mborres

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Отбор кожа/волосы/ногти:

In [10]:
skin = list(filter(lambda x: x.endswith('01_PEORRES'), listIN))
df_skin = pd.concat([df_base, df[skin]], axis=1)
df_skin

,SUBJ_SCREEN,V0_04_01_PEORRES,V2_03_01_PEORRES,V3_02_01_PEORRES,V4_02_01_PEORRES,V5_02_01_PEORRES
0,Скрининговый номер,Кожные покровы и видимые слизистые,Кожные покровы и видимые слизистые,Кожные покровы и видимые слизистые,Кожные покровы и видимые слизистые,Кожные покровы и видимые слизистые
1,01001,"Отклонение, связано с анамнезом",Норма,Норма,NaN,NaN
2,01002,"Отклонение, связано с анамнезом",Норма,Норма,NaN,NaN
3,01003,"Отклонение, связано с анамнезом",Норма,Норма,NaN,NaN
4,01004,"Отклонение, связано с анамнезом",Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Эндокринная система:

In [11]:
end = list(filter(lambda x: x.endswith('02_PEORRES'), listIN))
df_end = pd.concat([df_base, df[end]], axis=1)
df_end

,SUBJ_SCREEN,V0_04_02_PEORRES,V2_03_02_PEORRES,V3_02_02_PEORRES,V4_02_02_PEORRES,V5_02_02_PEORRES
0,Скрининговый номер,Эндокринная система,Эндокринная система,Эндокринная система,Эндокринная система,Эндокринная система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор ЛОР-органы:

In [12]:
lor = list(filter(lambda x: x.endswith('03_PEORRES'), listIN))
df_lor = pd.concat([df_base, df[lor]], axis=1)
df_lor

,SUBJ_SCREEN,V0_04_03_PEORRES,V2_03_03_PEORRES,V3_02_03_PEORRES,V4_02_03_PEORRES,V5_02_03_PEORRES
0,Скрининговый номер,Лимфатическая система,Лимфатическая система,Лимфатическая система,Лимфатическая система,Лимфатическая система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Сердечно-сосудистая система:

In [13]:
heart = list(filter(lambda x: x.endswith('04_PEORRES'), listIN))
df_heart = pd.concat([df_base, df[heart]], axis=1)
df_heart

,SUBJ_SCREEN,V0_04_04_PEORRES,V2_03_04_PEORRES,V3_02_04_PEORRES,V4_02_04_PEORRES,V5_02_04_PEORRES
0,Скрининговый номер,ЛОР-органы,ЛОР-органы,ЛОР-органы,ЛОР-органы,ЛОР-органы
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Дыхательная система:

In [14]:
breath = list(filter(lambda x: x.endswith('05_PEORRES'), listIN))
df_breath = pd.concat([df_base, df[breath]], axis=1)
df_breath

,SUBJ_SCREEN,V0_04_05_PEORRES,V2_03_05_PEORRES,V3_02_05_PEORRES,V4_02_05_PEORRES,V5_02_05_PEORRES
0,Скрининговый номер,Дыхательная система,Дыхательная система,Дыхательная система,Дыхательная система,Дыхательная система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Лимфатическая система:

In [15]:
limf = list(filter(lambda x: x.endswith('06_PEORRES'), listIN))
df_limf = pd.concat([df_base, df[limf]], axis=1)
df_limf

,SUBJ_SCREEN,V0_04_06_PEORRES,V2_03_06_PEORRES,V3_02_06_PEORRES,V4_02_06_PEORRES,V5_02_06_PEORRES
0,Скрининговый номер,Сердечно-сосудистая система,Сердечно-сосудистая система,Сердечно-сосудистая система,Сердечно-сосудистая система,Сердечно-сосудистая система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Желудочно-кишечный тракт:

In [16]:
stom = list(filter(lambda x: x.endswith('07_PEORRES'), listIN))
df_stom = pd.concat([df_base, df[stom]], axis=1)
df_stom

,SUBJ_SCREEN,V0_04_07_PEORRES,V2_03_07_PEORRES,V3_02_07_PEORRES,V4_02_07_PEORRES,V5_02_07_PEORRES
0,Скрининговый номер,Желудочно-кишечный тракт,Желудочно-кишечный тракт,Желудочно-кишечный тракт,Желудочно-кишечный тракт,Желудочно-кишечный тракт
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Нервная система:

In [17]:
nerf = list(filter(lambda x: x.endswith('08_PEORRES'), listIN))
df_nerf = pd.concat([df_base, df[nerf]], axis=1)
df_nerf

,SUBJ_SCREEN,V0_04_08_PEORRES,V2_03_08_PEORRES,V3_02_08_PEORRES,V4_02_08_PEORRES,V5_02_08_PEORRES
0,Скрининговый номер,Нервная система,Нервная система,Нервная система,Нервная система,Нервная система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Костно-мышечная система:

In [18]:
bon = list(filter(lambda x: x.endswith('09_PEORRES'), listIN))
df_bon = pd.concat([df_base, df[bon]], axis=1)
df_bon

,SUBJ_SCREEN,V0_04_09_PEORRES,V2_03_09_PEORRES,V3_02_09_PEORRES,V4_02_09_PEORRES,V5_02_09_PEORRES
0,Скрининговый номер,Костно-мышечная система,Костно-мышечная система,Костно-мышечная система,Костно-мышечная система,Костно-мышечная система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор Мочевыделительная система:

In [19]:
pee = list(filter(lambda x: x.endswith('10_PEORRES'), listIN))
df_pee = pd.concat([df_base, df[pee]], axis=1)
df_pee

,SUBJ_SCREEN,V0_04_10_PEORRES,V2_03_10_PEORRES,V3_02_10_PEORRES,V4_02_10_PEORRES,V5_02_10_PEORRES
0,Скрининговый номер,Репродуктивная система,Репродуктивная система,Репродуктивная система,Репродуктивная система,Репродуктивная система
1,01001,Норма,Норма,Норма,NaN,NaN
2,01002,Норма,Норма,Норма,NaN,NaN
3,01003,Норма,Норма,Норма,NaN,NaN
4,01004,Норма,Норма,Норма,NaN,NaN
...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN

Отбор тест на алкоголь:

In [20]:
eth = list(filter(lambda x: x.endswith('ETHANOL_LBORRES'), listIN))
df_eth = pd.concat([df_base, df[eth]], axis=1)
df_eth

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Отбор тестов на наркотики:

In [21]:
mor = list(filter(lambda x: x.endswith('MORPH_LBORRES'), listIN))
df_nar = pd.concat([df_base, df[mor]], axis=1)
can = list(filter(lambda x: x.endswith('CANNAB_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[can]], axis=1)
amp = list(filter(lambda x: x.endswith('AMPH_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[amp]], axis=1)
met = list(filter(lambda x: x.endswith('METH_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[met]], axis=1)
coc = list(filter(lambda x: x.endswith('COC_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[coc]], axis=1)
ben = list(filter(lambda x: x.endswith('BENZOD_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[ben]], axis=1)
bar = list(filter(lambda x: x.endswith('BARB_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[bar]], axis=1)
ext = list(filter(lambda x: x.endswith('EXT_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[ext]], axis=1)
met = list(filter(lambda x: x.endswith('METAD_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[met]], axis=1)
fen = list(filter(lambda x: x.endswith('FENC_LBORRES'), listIN))
df_nar = pd.concat([df_nar, df[fen]], axis=1)

df_nar

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Отбор мочи на котинин:

In [22]:
cot = list(filter(lambda x: x.endswith('COTININE_LBORRES'), listIN))
df_cot = pd.concat([df_base, df[cot]], axis=1)
df_cot

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Отбор теста на беременность:

In [23]:
df_base_plus=df[['SUBJ_SCREEN','V0_02_SEX']]
hcg = list(filter(lambda x: x.endswith('HCG_LBORRES'), listIN))
df_hcg = pd.concat([df_base_plus, df[hcg]], axis=1)
df_hcg

,SUBJ_SCREEN,V0_02_SEX,V0_13_HCG_LBORRES,V3_10_HCG_LBORRES,V4_10_HCG_LBORRES,V5_10_HCG_LBORRES
0,Скрининговый номер,Пол,Анализ мочи на β-ХГЧ,Анализ мочи на β-ХГЧ,Анализ мочи на β-ХГЧ,Анализ мочи на β-ХГЧ
1,01001,Женский,NaN,NaN,NaN,NaN
2,01002,Мужской,NaN,NaN,NaN,NaN
3,01003,Мужской,NaN,NaN,NaN,NaN
4,01004,Мужской,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
492,48010,Мужской,NaN,NaN,NaN,NaN
493,48011,Мужской,NaN,NaN,NaN,NaN
494,48012,Женский,NaN,NaN,NaN,NaN
495,48013,Мужской,NaN,NaN,NaN,NaN
496,48014,Женский,NaN,NaN,NaN,NaN

Серологические тесты:

In [24]:
hb = list(filter(lambda x: x.endswith('HB_LBORRES'), listIN))
df_ser = pd.concat([df_base, df[hb]], axis=1)
hcv = list(filter(lambda x: x.endswith('HCV_LBORRES'), listIN))
df_ser = pd.concat([df_ser, df[hcv]], axis=1)
hiv = list(filter(lambda x: x.endswith('HIV_LBORRES'), listIN))
df_ser = pd.concat([df_ser, df[hiv]], axis=1)
rpr = list(filter(lambda x: x.endswith('RPR_LBORRES'), listIN))
df_ser = pd.concat([df_ser, df[rpr]], axis=1)

df_ser

,SUBJ_SCREEN,V0_10_HB_LBORRES,V0_10_HCV_LBORRES,V0_10_HIV_LBORRES,V0_10_RPR_LBORRES
0,Скрининговый номер,Поверхностный антиген вируса гепатита B (каче...,Антитела к антигенам вируса гепатита C (качест...,Антитела к ВИЧ-1/2 (качественный анализ на ан...,"Сифилис (Treponema pallidum, антитела, ИФА)"
1,01001,Отрицательный,Отрицательный,Отрицательный,Отрицательный
2,01002,Отрицательный,Отрицательный,Отрицательный,Отрицательный
3,01003,Отрицательный,Отрицательный,Отрицательный,Отрицательный
4,01004,Отрицательный,Отрицательный,Отрицательный,Отрицательный
...,...,...,...,...,...
492,48010,Отрицательный,Отрицательный,Отрицательный,Отрицательный
493,48011,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN

Отбор полей "Другое":

In [25]:
oth = list(filter(lambda x: x.endswith('OTH'), listIN))
df_oth = pd.concat([df_base, df[oth]], axis=1)
df_oth

            SUBJ_SCREEN         V0_02_RACEOTH EOS_01_DISCONT_OTH
0    Скрининговый номер  Если другая, укажите            Укажите
1                 01001                   NaN                NaN
2                 01002                   NaN                NaN
3                 01003                   NaN                NaN
4                 01004                   NaN                NaN
..                  ...                   ...                ...
492               48010                   NaN                NaN
493               48011                   NaN                NaN
494               48012                   NaN                NaN
495               48013                   NaN                NaN
496               48014                   NaN                NaN

[497 rows x 3 columns]

Отбор регистрации новых нежелательных являений:

In [26]:
aeoccur = list(filter(lambda x: x.endswith('AEOCCUR'), listIN))
df_aeoccur = pd.concat([df_base, df[aeoccur]], axis=1)
df_aeoccur

,SUBJ_SCREEN,V0_18_AEOCCUR,V1_07_AEOCCUR,V2_06_AEOCCUR,T1_03_AEOCCUR,V3_15_AEOCCUR,T2_03_AEOCCUR,T3_03_AEOCCUR,T4_03_AEOCCUR,T5_03_AEOCCUR,V4_17_AEOCCUR,V5_17_AEOCCUR
0,Скрининговый номер,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...,Были ли зарегистрированы новые нежелательные я...
1,01001,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Нет,NaN,NaN,NaN
2,01002,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Нет,NaN,NaN,NaN
3,01003,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Нет,NaN,NaN,NaN
4,01004,Нет,Нет,Нет,Нет,Нет,Нет,Нет,Нет,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
492,48010,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,48011,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Отбор комментариев к визиту:

In [27]:
corres = list(filter(lambda x: x.endswith('COORRES'), listIN))
df_corres = pd.concat([df_base, df[corres]], axis=1)
df_corres

,SUBJ_SCREEN,SD_02_COORRES,V0_20_COORRES,V1_08_COORRES,V2_07_COORRES,T1_04_COORRES,V3_16_COORRES,T2_04_COORRES,T3_04_COORRES,T4_04_COORRES,T5_04_COORRES,V4_18_COORRES,V5_18_COORRES
0,Скрининговый номер,Есть комментарии?,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии,Комментарии
1,01001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Отбор комментариев к анализам:

In [28]:
desc = list(filter(lambda x: x.endswith('DESC'), listIN))
df_desc = pd.concat([df_base, df[desc]], axis=1)
df_desc

,SUBJ_SCREEN,SD_02_RFICCH_CONFDESC,SD_02_RFICTM_CONFDESC,SD_02_CODESC,V0_03_DRUGS_SUDESC,V0_03_REPR_RPDESC,V0_04_01_PEDESC,V0_04_02_PEDESC,V0_04_03_PEDESC,V0_04_04_PEDESC,...,V5_07_GLUCUR_LBDESC,V5_07_RBCUR_LBDESC,V5_07_WBCUR_LBDESC,V5_07_PHUR_LBDESC,V5_07_BACTMI_LBDESC,V5_07_EPITHSQMI_LBDESC,V5_08_DMER_LBDESC,V5_11_HR_EGDESC,V5_11_EG_EGDESC,V5_13_ADHDIS_PEDESC
0,Скрининговый номер,"Если нет, уточните","Если нет, уточните","Если да, укажите",Уточните,Уточните причину,Поясните,Поясните,Поясните,Поясните,...,Комментарий,Комментарий,Комментарий,Комментарий,Комментарий,Комментарий,Комментарий,Комментарий,Поясните,"Если да, укажите все применимые проявления"
1,01001,NaN,NaN,NaN,NaN,Менопауза,При осмотре определяется выпиливание в параумб...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01002,NaN,NaN,NaN,NaN,NaN,При пальпации живота визуализируется грыжевое ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01003,NaN,NaN,NaN,NaN,NaN,При осмотре определяется выпячивание на передн...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01004,NaN,NaN,NaN,NaN,NaN,При осмотре визуализируется выпячивание параум...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,Менопауза,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,Гистерэктомия или перевязка маточных труб,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Отбор причин:

In [29]:
reas = list(filter(lambda x: x.endswith('REASND'), listIN))
df_reas = pd.concat([df_base, df[reas]], axis=1)
df_reas

,SUBJ_SCREEN,V0_04_PEREASND,V0_05_VSREASND,V0_06_LBREASND,V0_07_LBREASND,V0_08_LBREASND,V0_09_LBREASND,V0_10_LBREASND,V0_11_LBREASND,V0_12_LBREASND,...,V5_05_LBREASND,V5_06_LBREASND,V5_07_LBREASND,V5_08_LBREASND,V5_09_LBREASND,V5_10_LBREASND,V5_11_EGREASND,V5_12_QSREASND,V5_13_PEREASND,V5_14_PRREASND
0,Скрининговый номер,"Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину",...,"Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину","Если процедура не проведена, укажите причину",Укажите причину,"Если процедура не проведена, укажите причину"
1,01001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,48010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,48011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,48012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,48013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,48014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Отбор приёма препарата:

In [30]:
extrt = list(filter(lambda x: x.endswith('EXTRT'), listIN))
df_extrt = pd.concat([df_base, df[extrt]], axis=1)
df_extrt

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Проверка на приём пищи:

In [31]:
mlo = list(filter(lambda x: x.endswith('MLORRES'), listIN))
df_mlo = pd.concat([df_base, df[mlo]], axis=1)
df_mlo

            SUBJ_SCREEN
0    Скрининговый номер
1                 01001
2                 01002
3                 01003
4                 01004
..                  ...
492               48010
493               48011
494               48012
495               48013
496               48014

[497 rows x 1 columns]

Отбор Общих форм:

In [8]:
df_O=pd.read_excel('2023-10-12 11_43_22.xlsx', sheet_name = 'Общие формы')
df_O

,SUBJ_ID,SITE_ID,SUBJ_SCREEN,RAND_NUM,INIT,FINSTAT,BLOCK,DEL,01_MHTERM,01_MHSTDAT,...,18_ADHNUM_B_PRORRES,18_ADHNUM_C_PRORRES,18_ADHNUM_D_PRORRES,18_ADHNUM_E_PRORRES,18_ADHNUM_F_PRORRES,18_ADHNUM_G_PRORRES,18_ADHNUM_H_PRORRES,18_ADHNUM_I_PRORRES,18_ADHNUM_TOTAL_PRORRES,INVESTIGATOR_SIGNATURE
0,Код субъекта,Номер центра,Скрининговый номер,Рандомизационный код,Инициалы Пациента,NaN,NaN,NaN,Состояние / диагноз / операция,Дата начала,...,Количество спаек в квадранте B,Количество спаек в квадранте C,Количество спаек в квадранте D,Количество спаек в квадранте E,Количество спаек в квадранте F,Количество спаек в квадранте G,Количество спаек в квадранте H,Количество спаек в квадранте I,Автоматический расчет: Общее количество спаек,Подпись исследователя
1,7160,03,03036,998,NaN,NaN,NaN,NaN,"Дивертикулит, перфорация дивертикула, состояни...",2021-12-??,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7160,03,03036,998,NaN,NaN,NaN,NaN,Ишемическая болезнь сердца: постинфарктный кар...,2021-01-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7160,03,03036,998,NaN,NaN,NaN,NaN,Синдром Жильбера,????-??-??,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7160,03,03036,998,NaN,NaN,NaN,NaN,"Операция: Резекция культи прямой кишки, развор...",2023-04-28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5246,7227,03,03043,812,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5247,7651,01,01035,199,NaN,NaN,NaN,NaN,послеоперационная центральная грыжа,2026-06-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5248,7190,08,08069,193,NaN,NaN,NaN,NaN,опухоль хвоста поджелудочной железы,2023-??-??,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5249,7190,08,08069,193,NaN,NaN,NaN,NaN,кисты печени,2023-??-??,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5250,7190,08,08069,193,NaN,NaN,NaN,NaN,артериальная гипертензия 2 ст,????-??-??,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
listIN=list(df_O.columns)

In [10]:
listIN

['SUBJ_ID',
 'SITE_ID',
 'SUBJ_SCREEN',
 'RAND_NUM',
 'INIT',
 'FINSTAT',
 'BLOCK',
 'DEL',
 '01_MHTERM',
 '01_MHSTDAT',
 '01_MHENDAT',
 '01_MHONGO',
 '02_CMSTDAT',
 '02_CMENDAT',
 '02_CMONGO',
 '02_CMCAT',
 '02_CMTRT',
 '02_CMINGRD',
 '02_CMDOS',
 '02_CMDOSU',
 '02_CMDOSUOTH',
 '02_CMFORM',
 '02_CMFORMOTH',
 '02_CMROUTE',
 '02_CMROUTEOTH',
 '02_CMFREQ',
 '02_CMFREQOTH',
 '02_CMINDC',
 '03_AETERM',
 '03_AEDESC',
 '03_AESTDTC',
 '03_AEENDTC',
 '03_AEONGO',
 '03_AESER',
 '03_SAELBL',
 '03_SAE_CRIT',
 '03_SDTHDAT',
 '03_SMIE',
 '03_AESEV',
 '03_AERELIP_YN',
 '03_AERELIP',
 '03_AEEXPECT',
 '03_AEACT',
 '03_AEACT_CM',
 '03_CM',
 '03_AEOUT',
 '03_SAE_SIG',
 '04_SVUPDES',
 '04_SVSTDAT',
 '04_SVCOMPL',
 '04_SVORRES',
 '04_PROCCUR',
 '04_PRORRES',
 '04_AEOCCUR',
 '04_AE',
 '04_CMOCCUR',
 '04_CM',
 '05_VSDTC',
 '05_SYSBP_VSORRES',
 '05_SYSBP_VSORRESU',
 '05_SYSBP_VSRES',
 '05_SYSBP_VSDESC',
 '05_DIABP_VSORRES',
 '05_DIABP_VSORRESU',
 '05_DIABP_VSRES',
 '05_DIABP_VSDESC',
 '05_HR_VSORRES',
 '05_HR_VSORRESU',
 '05_HR_VSRES',
 '05_HR_VSDESC',
 '05_RR_VSORRES',
 '05_RR_VSORRESU',
 '05_RR_VSRES',
 '05_RR_VSDESC',
 '05_TEMP_VSORRES',
 '05_TEMP_VSORRESU',
 '05_TEMP_VSRES',
 '05_TEMP_VSDESC',
 '15_PEDTC',
 '15_01_PEORRES',
 '15_01_PEDESC_MH',
 '15_01_MH',
 '15_01_PEDESC_AE',
 '15_01_AE',
 '15_01_PEDESC',
 '15_02_PEORRES',
 '15_02_PEDESC_MH',
 '15_02_MH',
 '15_02_PEDESC_AE',
 '15_02_AE',
 '15_02_PEDESC',
 '15_03_PEORRES',
 '15_03_PEDESC_MH',
 '15_03_MH',
 '15_03_PEDESC_AE',
 '15_03_AE',
 '15_03_PEDESC',
 '15_04_PEORRES',
 '15_04_PEDESC_MH',
 '15_04_MH',
 '15_04_PEDESC_AE',
 '15_04_AE',
 '15_04_PEDESC',
 '15_05_PEORRES',
 '15_05_PEDESC_MH',
 '15_05_MH',
 '15_05_PEDESC_AE',
 '15_05_AE',
 '15_05_PEDESC',
 '15_06_PEORRES',
 '15_06_PEDESC_MH',
 '15_06_MH',
 '15_06_PEDESC_AE',
 '15_06_AE',
 '15_06_PEDESC',
 '15_07_PEORRES',
 '15_07_PEDESC_MH',
 '15_07_MH',
 '15_07_PEDESC_AE',
 '15_07_AE',
 '15_07_PEDESC',
 '15_08_PEORRES',
 '15_08_PEDESC_MH',
 '15_08_MH',
 '15_08_PEDESC_AE',
 '15_08_AE',
 '15_08_PEDESC',
 '15_09_PEORRES',
 '15_09_PEDESC_MH',
 '15_09_MH',
 '15_09_PEDESC_AE',
 '15_09_AE',
 '15_09_PEDESC',
 '15_10_PEORRES',
 '15_10_PEDESC_MH',
 '15_10_MH',
 '15_10_PEDESC_AE',
 '15_10_AE',
 '15_10_PEDESC',
 '15_11_PEORRES',
 '15_11_PEDESC_MH',
 '15_11_MH',
 '15_11_PEDESC_AE',
 '15_11_AE',
 '15_11_PEDESC',
 '06_EGDTC',
 '06_HR_EGORRES',
 '06_HR_EGORRESU',
 '06_HR_EGRES',
 '06_HR_EGDESC',
 '06_EG_EGRES',
 '06_EG_EGDESC_MH',
 '06_EG_MH',
 '06_EG_EGDESC_AE',
 '06_EG_AE',
 '06_EG_EGPEDESC',
 '07_LBDTC',
 '07_LBFAST',
 '07_LBFAST_DESC',
 '07_ESR_LBORRES',
 '07_ESR_LBORRESU',
 '07_ESR_LBRES',
 '07_ESR_LBDESC',
 '07_HCT_LBORRES',
 '07_HCT_LBORRESU',
 '07_HCT_LBRES',
 '07_HCT_LBDESC',
 '07_HGB_LBORRES',
 '07_HGB_LBORRESU',
 '07_HGB_LBRES',
 '07_HGB_LBDESC',
 '07_RBC_LBORRES',
 '07_RBC_LBORRESU',
 '07_RBC_LBRES',
 '07_RBC_LBDESC',
 '07_PLAT_LBORRES',
 '07_PLAT_LBORRESU',
 '07_PLAT_LBRES',
 '07_PLAT_LBDESC',
 '07_WBC_LBORRES',
 '07_WBC_LBORRESU',
 '07_WBC_LBRES',
 '07_WBC_LBDESC',
 '07_LBL',
 '07_NEUTBLE_LBORRES',
 '07_NEUTBLE_LBORRESU',
 '07_NEUTBLE_LBRES',
 '07_NEUTBLE_LBDESC',
 '07_NEUTB_LBORRES',
 '07_NEUTB_LBORRESU',
 '07_NEUTB_LBRES',
 '07_NEUTB_LBDESC',
 '07_NEUTSGLE_LBORRES',
 '07_NEUTSGLE_LBORRESU',
 '07_NEUTSGLE_LBRES',
 '07_NEUTSGLE_LBDESC',
 '07_NEUTSG_LBORRES',
 '07_NEUTSG_LBORRESU',
 '07_NEUTSG_LBRES',
 '07_NEUTSG_LBDESC',
 '07_EOSLE_LBORRES',
 '07_EOSLE_LBORRESU',
 '07_EOSLE_LBRES',
 '07_EOSLE_LBDESC',
 '07_EOS_LBORRES',
 '07_EOS_LBORRESU',
 '07_EOS_LBRES',
 '07_EOS_LBDESC',
 '07_BASOLE_LBORRES',
 '07_BASOLE_LBORRESU',
 '07_BASOLE_LBRES',
 '07_BASOLE_LBDESC',
 '07_BASO_LBORRES',
 '07_BASO_LBORRESU',
 '07_BASO_LBRES',
 '07_BASO_LBDESC',
 '07_MONOLE_LBORRES',
 '07_MONOLE_LBORRESU',
 '07_MONOLE_LBRES',
 '07_MONOLE_LBDESC',
 '07_MONO_LBORRES',
 '07_MONO_LBORRESU',
 '07_MONO_LBRES',
 '07_MONO_LBDESC',
 '07_LYMLE_LBORRES',
 '07_LYMLE_LBORRESU',
 '07_LYMLE_LBRES',
 '07_LYMLE_LBDESC',
 '07_LYM_LBORRES',
 '07_LYM_LBORRESU',
 '07_LYM_LBRES',
 '07_LYM_LBDESC',
 '08_LBDTC',
 '08_LBFAST',
 '08_LBFAST_DESC',
 '08_ALT_LBORRES',
 '08_ALT_LBORRESU',
 '08_ALT_LBRES',
 '08_ALT_LBDESC',
 '08_AST_LBORRES',
 '08_AST_LBORRESU',
 '08_AST_LBRES',
 '08_AST_LBDESC',
 '08_GGT_LBORRES',
 '08_GGT_LBORRESU',
 '08_GGT_LBRES',
 '08_GGT_LBDESC',
 '08_ALP_LBORRES',
 '08_ALP_LBORRESU',
 '08_ALP_LBRES',
 '08_ALP_LBDESC',
 '08_BILI_LBORRES',
 '08_BILI_LBORRESU',
 '08_BILI_LBRES',
 '08_BILI_LBDESC',
 '08_BILIDIR_LBORRES',
 '08_BILIDIR_LBORRESU',
 '08_BILIDIR_LBRES',
 '08_BILIDIR_LBDESC',
 '08_CREAT_LBORRES',
 '08_CREAT_LBORRESU',
 '08_CREAT_LBRES',
 '08_CREAT_LBDESC',
 '08_UREA_LBORRES',
 '08_UREA_LBORRESU',
 '08_UREA_LBRES',
 '08_UREA_LBDESC',
 '08_GLUC_LBORRES',
 '08_GLUC_LBORRESU',
 '08_GLUC_LBRES',
 '08_GLUC_LBDESC',
 '08_PROT_LBORRES',
 '08_PROT_LBORRESU',
 '08_PROT_LBRES',
 '08_PROT_LBDESC',
 '16_LBDTC',
 '16_INR_LBORRES',
 '16_INR_LBORRESU',
 '16_INR_LBRES',
 '16_INR_LBDESC',
 '16_APTT_LBORRES',
 '16_APTT_LBORRESU',
 '16_APTT_LBRES',
 '16_APTT_LBDESC',
 '16_FIBR_LBORRES',
 '16_FIBR_LBORRESU',
 '16_FIBR_LBRES',
 '16_FIBR_LBDESC',
 '17_LBDTC',
 '17_DMER_LBORRES',
 '17_DMER_LBORRESU',
 '17_DMER_LBRES',
 '17_DMER_LBDESC',
 '09_LBDTC',
 '09_PROTUR_LBORRES',
 '09_PROTUR_LBORRESU',
 '09_PROTUR_LBRES',
 '09_PROTUR_LBDESC',
 '09_GLUCUR_LBORRES',
 '09_GLUCUR_LBORRESU',
 '09_GLUCUR_LBRES',
 '09_GLUCUR_LBDESC',
 '09_RBCUR_LBORRES',
 '09_RBCUR_LBORRESU',
 '09_RBCUR_LBRES',
 '09_RBCUR_LBDESC',
 '09_WBCUR_LBORRES',
 '09_WBCUR_LBORRESU',
 '09_WBCUR_LBRES',
 '09_WBCUR_LBDESC',
 '09_PHUR_LBORRES',
 '09_PHUR_LBORRESU',
 '09_PHUR_LBRES',
 '09_PHUR_LBDESC',
 '09_BACTMI_LBORRES',
 '09_BACTMI_LBORRESU',
 '09_BACTMI_LBRES',
 '09_BACTMI_LBDESC',
 '09_EPITHSQMI_LBORRES',
 '09_EPITHSQMI_LBORRESU',
 '09_EPITHSQMI_LBRES',
 '09_EPITHSQMI_LBDESC',
 '12_LBDTC',
 '12_HCG_LBORRES',
 '13_LBDTC',
 '13_HB_LBORRES',
 '13_HCV_LBORRES',
 '13_HIV_LBORRES',
 '13_RPR_LBORRES',
 '14_LBDTC',
 '14_COVID_LBORRES',
 '18_PRDTC',
 '18_ADH_PRYN',
 '18_ADH_PRORRES',
 '18_CONGLNUM_PRORRES',
 '18_ADH_PRLOC',
 '18_ADHNUM_A_PRORRES',
 '18_ADHNUM_B_PRORRES',
 '18_ADHNUM_C_PRORRES',
 '18_ADHNUM_D_PRORRES',
 '18_ADHNUM_E_PRORRES',
 '18_ADHNUM_F_PRORRES',
 '18_ADHNUM_G_PRORRES',
 '18_ADHNUM_H_PRORRES',
 '18_ADHNUM_I_PRORRES',
 '18_ADHNUM_TOTAL_PRORRES',
 'INVESTIGATOR_SIGNATURE']

In [11]:
df_base=df_O[['SITE_ID','SUBJ_SCREEN']]

Отбор анамнеза:

In [12]:
MH = list(filter(lambda x: x.startswith('01'), listIN))
df_MH = pd.concat([df_base, df_O[MH]], axis=1)
df_MH.dropna(how = 'all', inplace = True, subset = ['01_MHTERM'])
df_MH

,SITE_ID,SUBJ_SCREEN,01_MHTERM,01_MHSTDAT,01_MHENDAT,01_MHONGO
0,Номер центра,Скрининговый номер,Состояние / диагноз / операция,Дата начала,Дата окончания,Продолжается
1,03,03036,"Дивертикулит, перфорация дивертикула, состояни...",2021-12-??,NaN,Да
2,03,03036,Ишемическая болезнь сердца: постинфарктный кар...,2021-01-16,NaN,Да
3,03,03036,Синдром Жильбера,????-??-??,NaN,Да
4,03,03036,"Операция: Резекция культи прямой кишки, развор...",2023-04-28,2023-04-28,Нет
...,...,...,...,...,...,...
5215,03,03043,Оперативное лечение: Внутрибрюшная резекция пр...,2023-05-05,2023-05-05,Нет
5247,01,01035,послеоперационная центральная грыжа,2026-06-01,NaN,Да
5248,08,08069,опухоль хвоста поджелудочной железы,2023-??-??,NaN,Да
5249,08,08069,кисты печени,2023-??-??,NaN,Да
5250,08,08069,артериальная гипертензия 2 ст,????-??-??,NaN,Да

Отбор терапии:

In [13]:
CM = list(filter(lambda x: x.startswith('02'), listIN))
df_CM = pd.concat([df_base, df_O[CM]], axis=1)
df_CM.dropna(how = 'all', inplace = True,subset = ['02_CMCAT'])
df_CM

,SITE_ID,SUBJ_SCREEN,02_CMSTDAT,02_CMENDAT,02_CMONGO,02_CMCAT,02_CMTRT,02_CMINGRD,02_CMDOS,02_CMDOSU,02_CMDOSUOTH,02_CMFORM,02_CMFORMOTH,02_CMROUTE,02_CMROUTEOTH,02_CMFREQ,02_CMFREQOTH,02_CMINDC
0,Номер центра,Скрининговый номер,Дата начала,Дата окончания,Прием препарата продолжается,Тип терапии,Торговое название,МНН - международное непатентованное название,Разовая доза,Единицы дозы (в пересчете на активное вещество),"Если ответ «Другое», укажите",Форма,"Если ответ «Другое», укажите",Путь введения,"Если ответ «Другое», укажите",Кратность приема,"Если ответ «Другое», укажите",Показания для назначения
1,03,03036,2021-01-??,NaN,Да,Сопутствующая,Бисопролол,Бисопролол,2.5,мг,NaN,Таблетки,NaN,Перорально,NaN,1 раз в сутки,NaN,"Артериальная гипертензия, ИБС"
2,03,03036,2021-01-??,NaN,Да,Сопутствующая,Розувастатин,Розувастатин,10,мг,NaN,Таблетки,NaN,Перорально,NaN,1 раз в сутки,NaN,Гиполипидемическая терапия
3,03,03036,2021-01-??,NaN,Да,Сопутствующая,Престариум,Периндоприла аргинин,5,мг,NaN,Таблетки,NaN,Перорально,NaN,1 раз в сутки,NaN,Гипертоническая болезнь
4,03,03036,2023-04-28,2023-04-28,Нет,Сопутствующая,Промедол,Тримеперидин,20,мг,NaN,Раствор,NaN,Внутримышечно,NaN,1 раз в сутки,NaN,Премедикация
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5242,03,03043,2023-05-09,2023-05-26,Нет,Сопутствующая,Омепразол,Омепразол,20,мг,NaN,Капсулы,NaN,Перорально,NaN,2 раза в сутки,NaN,Антисекреторная терапия
5243,03,03043,2023-05-11,2023-05-18,Нет,Сопутствующая,Гидрохлоротиазид,Гидрохлоротиазид,25,мг,NaN,Таблетки,NaN,Перорально,NaN,1 раз в сутки,NaN,Диуретическая терапия
5244,03,03043,2023-05-11,NaN,Да,Сопутствующая,Амлодипин,Амлодипин,10,мг,NaN,Таблетки,NaN,Перорально,NaN,1 раз в сутки,NaN,Гипотензивная терапия
5245,03,03043,2023-05-11,NaN,Да,Сопутствующая,Эналаприл,Эналаприл,20,мг,NaN,Таблетки,NaN,Перорально,NaN,2 раза в сутки,NaN,Гипотензивная терапия
5246,03,03043,2023-05-03,2023-05-18,Нет,Сопутствующая,Моксонидин,Моксонидин,0.2,мг,NaN,Таблетки,NaN,Перорально,NaN,2 раза в сутки,NaN,Гипотензивная терапия

Отбор НЯ:

In [14]:
AE = list(filter(lambda x: x.startswith('03'), listIN))
df_AE = pd.concat([df_base, df_O[AE]], axis=1)
df_AE.dropna(how = 'all', inplace = True,subset = ['03_AETERM'])
df_AE

,SITE_ID,SUBJ_SCREEN,03_AETERM,03_AEDESC,03_AESTDTC,03_AEENDTC,03_AEONGO,03_AESER,03_SAELBL,03_SAE_CRIT,...,03_SMIE,03_AESEV,03_AERELIP_YN,03_AERELIP,03_AEEXPECT,03_AEACT,03_AEACT_CM,03_CM,03_AEOUT,03_SAE_SIG
0,Номер центра,Скрининговый номер,Диагноз или симптом,Описание НЯ,Дата и время начала,Дата и время окончания,Продолжается на момент окончания участия в исс...,Серьезность,Информацию о СНЯ следует отправлять представит...,"Укажите все критерии серьезности, которые прим...",...,Поясните,Степень тяжести,Взаимосвязь НЯ с исследуемым препаратом,"Если да, уточните",Ожидаемость НЯ,Принятые меры в отношении добровольца и приема...,"Если ""Назначение другого лечения"", уточните","Если лекарственная терапия, укажите в общих фо...",Исход/разрешение НЯ,Подписать и отправить
1,03,03036,Правосторонняя сегментарная пневмония,Правосторонняя сегментарная пневмония,2023-05-01 14:00,2023-05-12 14:22,Нет,Несерьезное,NaN,NaN,...,NaN,Степень 1 - Легкая,Нет,NaN,Не применимо,Действий не требуется (продолжение исследовани...,NaN,NaN,Выздоровление/ прекращение НЯ,NaN
2,03,03036,Повышение АЛТ в крови,Повышение АЛТ в крови,2023-05-26 09:27,NaN,NaN,Несерьезное,NaN,NaN,...,NaN,Степень 2 - Умеренная,Да,Сомнительная,Непредвиденное НЯ,Действий не требуется (продолжение исследовани...,NaN,NaN,NaN,NaN
3,03,03036,Повышение АСТ в крови,Повышение АСТ в крови,2023-05-26 09:27,NaN,NaN,Несерьезное,NaN,NaN,...,NaN,Степень 2 - Умеренная,Да,Сомнительная,Непредвиденное НЯ,Действий не требуется (продолжение исследовани...,NaN,NaN,NaN,NaN
4,03,03036,Повышение концентрации Креатинина в крови,Повышение концентрации Креатинина в крови,2023-05-26 09:27,NaN,NaN,Несерьезное,NaN,NaN,...,NaN,Степень 2 - Умеренная,Да,Сомнительная,Непредвиденное НЯ,Действий не требуется (продолжение исследовани...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171,15,15015,Вторичный (панкреатогенный) сахарный диабет.,Повышение уровня глюкозы крови,2023-05-24 12:00,NaN,Да,Несерьезное,NaN,NaN,...,NaN,Степень 1 - Легкая,Да,Сомнительная,Непредвиденное НЯ,Действий не требуется (продолжение исследовани...,NaN,NaN,Неизвестно,NaN
5172,15,15015,"Панкреатическая фистула класса ""А"".",Альфа-амилаза отделяемого из брюшной полости 2...,2023-05-29 09:00,2023-06-22 16:28,Нет,Несерьезное,NaN,NaN,...,NaN,Степень 1 - Легкая,Да,Сомнительная,Непредвиденное НЯ,Действий не требуется (продолжение исследовани...,NaN,NaN,Выздоровление/ прекращение НЯ,NaN
5213,03,03043,Инфильтрат в малом тазу,Инфильтрат в малом тазу,2023-05-12 23:03,2023-05-22 15:20,Нет,Несерьезное,NaN,NaN,...,NaN,Степень 2 - Умеренная,Да,Сомнительная,Непредвиденное НЯ,Действий не требуется (продолжение исследовани...,NaN,NaN,Выздоровление/ прекращение НЯ,NaN
5214,03,03043,Тромбоэмболия субсегментарной артерии S3 левог...,Тромбоэмболия субсегментарной артерии S3 левог...,2023-05-16 15:46,2023-05-20 19:04,Нет,Несерьезное,NaN,NaN,...,NaN,Степень 1 - Легкая,Нет,NaN,Не применимо,Действий не требуется (продолжение исследовани...,NaN,NaN,Выздоровление/ прекращение НЯ,NaN
5215,03,03043,Нагноение послеоперационной раны,Нагноение послеоперационной раны,2023-05-15 15:00,2023-05-30 10:00,Нет,Несерьезное,NaN,NaN,...,NaN,Степень 1 - Легкая,Нет,NaN,Не применимо,Действий не требуется (продолжение исследовани...,NaN,NaN,Выздоровление/ прекращение НЯ,NaN

Листинг со всеми остальными ОФ:

In [15]:
df_otherOF = df_O.iloc[: , df_O.columns.get_loc('03_SAE_SIG')+1:]
df_otherOF

,04_SVUPDES,04_SVSTDAT,04_SVCOMPL,04_SVORRES,04_PROCCUR,04_PRORRES,04_AEOCCUR,04_AE,04_CMOCCUR,04_CM,...,18_ADHNUM_B_PRORRES,18_ADHNUM_C_PRORRES,18_ADHNUM_D_PRORRES,18_ADHNUM_E_PRORRES,18_ADHNUM_F_PRORRES,18_ADHNUM_G_PRORRES,18_ADHNUM_H_PRORRES,18_ADHNUM_I_PRORRES,18_ADHNUM_TOTAL_PRORRES,INVESTIGATOR_SIGNATURE
0,Причина проведения,Дата проведения,Наличие жалоб,Укажите,Процедуры проводились,"Укажите все процедуры, которые проводились",Были ли зарегистрированы новые нежелательные я...,Заполните раздел Нежелательные явления,Были зарегистрированы изменения в сопутствующе...,Заполните раздел Терапия,...,Количество спаек в квадранте B,Количество спаек в квадранте C,Количество спаек в квадранте D,Количество спаек в квадранте E,Количество спаек в квадранте F,Количество спаек в квадранте G,Количество спаек в квадранте H,Количество спаек в квадранте I,Автоматический расчет: Общее количество спаек,Подпись исследователя
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Запись в файл Эксель:

In [16]:
writer = pd.ExcelWriter('Serogard_Split_1.xlsx')

In [17]:
#df.to_excel(writer, 'Визиты', index= False)
df_O.to_excel(writer, 'Общие формы', index= False)

#df_dtc.to_excel(writer, 'DTC', index= False)
#df_dat.to_excel(writer, 'DAT', index= False)
#df_tim.to_excel(writer, 'TIM', index= False)

# df_mborres.to_excel(writer, 'Ковид', index= False)

# df_skin.to_excel(writer, 'Кожа,волосы,ногти', index= False)
# df_end.to_excel(writer, 'Эндокринная система', index= False)
# df_lor.to_excel(writer, 'ЛОР-органы', index= False)
# df_heart.to_excel(writer, 'Сердечно-сосудистая система', index= False)
# df_breath.to_excel(writer, 'Дыхательная система', index= False)
# df_limf.to_excel(writer, 'Лимфатическая система', index= False)
# df_stom.to_excel(writer, 'Желудочно-кишечный тракт', index= False)
# df_nerf.to_excel(writer, 'Нервная система', index= False)
# df_bon.to_excel(writer, 'Костно-мышечная система', index= False)
# df_pee.to_excel(writer, 'Мочевыделительная система', index= False)

# df_eth.to_excel(writer, 'Тест_Алкоголь', index= False)

# df_nar.to_excel(writer, 'Тест_Наркотики', index= False)

# df_cot.to_excel(writer, 'Тест_Котинин', index= False)

# df_hcg.to_excel(writer, 'Тест_Беременность', index= False)

# df_ser.to_excel(writer, 'Тест_Серология', index= False)

# df_oth.to_excel(writer, 'Другое', index= False)

# df_aeoccur.to_excel(writer, 'Новые_НЯ', index= False)

# df_corres.to_excel(writer, 'Комментарии', index= False)

# df_desc.to_excel(writer, 'Комментарии_1', index= False)

# df_reas.to_excel(writer, 'Причины', index= False)

# df_extrt.to_excel(writer, 'Препарат', index= False)

# df_mlo.to_excel(writer, 'Выписка', index= False)

df_MH.to_excel(writer, 'Анамнез_ОФ', index= False)
df_CM.to_excel(writer, 'Терапия_ОФ', index= False)
df_AE.to_excel(writer, 'НЯ_ОФ', index= False)
df_otherOF.to_excel(writer, 'Внеплановые_ОФ', index= False)

In [ ]:
writer.save()